### ISSUE TITLE
RuntimeError: Couldn't find Minecraft Version "latest" in manifest file

### ISSUE THREAD

**Issue by nyokinyoki** [mide/minecraft-overviewer#113]
I'm trying to run a fresh container using docker compose:
```
version: '2'
services:
  minecraft-overviewer-app:
    image: mide/minecraft-overviewer:latest
    container_name: minecraft-overviewer-app
    environment:
      - MINECRAFT_VERSION="latest"

    volumes:
      - /var/lib/docker/volumes/minecraft_data/_data/:/home/minecraft/server/:ro
      - ./data/map/:/home/minecraft/render/:rw
      - ./data/minecraft/:/home/minecraft/.minecraft/:rw

  minecraft-overviewer-nginx:
    image: docker.io/bitnami/nginx:latest
    container_name: minecraft-overviewer-nginx
    restart: unless-stopped
    volumes:
      - ./data/map/:/app
    ports:
      - '82:8080'
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overviewer.entrypoints=http"
      - "traefik.http.routers.overviewer.rule=Host(`example.com`)"
      - "traefik.http.middlewares.overviewer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overviewer.middlewares=overviewer-https-redirect"
      - "traefik.http.routers.overviewer-secure.entrypoints=https"
      - "traefik.http.routers.overviewer-secure.rule=Host(`example.com`)"
      - "traefik.http.routers.overviewer-secure.tls=true"
      - "traefik.http.routers.overviewer-secure.service=overviewer"
      - "traefik.http.services.overviewer.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```
But the container stops with the following error in logs:
```
# docker logs minecraft-overviewer-app
Traceback (most recent call last):
  File "/home/minecraft/download_url.py", line 52, in <module>
    print(get_minecraft_download_url(args.version))
  File "/home/minecraft/download_url.py", line 30, in get_minecraft_download_url
    version, MANIFEST_URL
RuntimeError: Couldn't find Minecraft Version "latest" in manifest file https://launchermeta.mojang.com/mc/game/version_manifest.json.
```
Using version numbers, for example `1.18.2` doesn't work either, it throws the same exception.

**Comment by jguizarj** [comment]
Hi @nyokinyoki ! I've tried to replicate the error using

`docker run   --rm   -e MINECRAFT_VERSION="1.18.2"   -v /home/user/minecraft/data:/home/minecraft/server/:ro  -v /home/usrer/render/:/home/minecraft/render/:rw mide/minecraft-overviewer:`

I had no problem running overviewer, I think the problem is in the `./data/minecraft/:/home/minecraft/.minecraft/:rw` volume

The python start script will try to download the textures in the `.minecraft` path

Are you trying to use custom textures? if not I'll recommend removing that volume configuration from the docker compose file

**Comment by nyokinyoki** [comment]
Hey, @jguizarj.

No, I didn't plan on using custom textures at all, I was simply trying to avoid downloading minecraft jar every time the container runs if it isn't necessary. It's mentioned in a [entrypoint.sh comment](https://github.com/mide/minecraft-overviewer/blob/808ffc3920c87d351fd5d4a409508fa871f23c8e/entrypoint.sh#L18).

In either case, I'm getting the same exception if I comment out .minecraft volume in my docker compose YAML.

**Comment by jguizarj** [comment]
I see. The problem is in the environment variable syntax

You could try replacing `- MINECRAFT_VERSION="latest"` with `MINECRAFT_VERSION: "1.18.2"`

I've just rendered a map using Docker Compose version v2.4.1:

```
version: "3.8"

  overviewer:
    image: mide/minecraft-overviewer
    container_name: overviewer
    environment:
      MINECRAFT_VERSION: "1.18.2"

    volumes:
      - ./data:/home/minecraft/server/:ro
      - ./render/:/home/minecraft/render/:rw
```

`docker compose run overviewer`
