### ISSUE TITLE
Error after starting container: Couldn't find Minecraft Version "1.15.2" in manifest file

### ISSUE THREAD

**Issue by anLizard** [mide/minecraft-overviewer#51]
Hi there, I set the environment variable `MINECRAFT_VERSION="1.15.2"`, but right after starting the docker container I get
```

mcov     | Traceback (most recent call last):
mcov     |   File "/home/minecraft/download_url.py", line 39, in <module>
mcov     |     print(get_minecraft_download_url(args.version))
mcov     |   File "/home/minecraft/download_url.py", line 23, in get_minecraft_download_url
mcov     |     raise RuntimeError("Couldn't find Minecraft Version {} in manifest file {}.".format(version, MANIFEST_URL))
mcov     | RuntimeError: Couldn't find Minecraft Version "1.15.2" in manifest file https://launchermeta.mojang.com/mc/game/version_manifest.json.
mcov exited with code 1
```
There is internet access, and the version exists in the manifest file... Not sure what to do here, please help!

**Comment by mide** [comment]
That's odd, I'll take a look.

**Comment by mide** [comment]
One thing I noticed at quick glance (sorry I haven't had more time) is that your version is quoted in the error message.

```
RuntimeError: Couldn't find Minecraft Version "1.15.2" in manifest file
```

The source code doesn't add the quotes into the log message so I wonder if you're using [smart quotes](https://devblogs.microsoft.com/oldnewthing/20090225-00/?p=19033), and thats what is messing you up.
https://github.com/mide/minecraft-overviewer/blob/d2fad05fb06a30d6ef40214562e08ad41b8c33b0/download_url.py#L23

**Comment by mide** [comment]
I'll leave this issue open for a few days, if you continue to have an issue, let me know. Thanks!

**Comment by anLizard** [comment]
Thanks, that fixed this issue for me, but now I am running into a different problem...

```
mcov-minecraft         | 2020-03-05 10:10:18 (47.0 MB/s) - '1.15.2.jar' saved [15531492/15531492]
mcov-minecraft         |
mcov-minecraft         | 2020-03-05 10:10:18  Welcome to Minecraft Overviewer!
mcov-minecraft         | *******************************************************************************
mcov-minecraft         | 2020-03-05 10:10:18 E An error has occurred. This may be a bug. Please let us know!
mcov-minecraft         | See http://docs.overviewer.org/en/latest/index.html#help
mcov-minecraft         |
mcov-minecraft         | This is the error that occurred:
mcov-minecraft         | Traceback (most recent call last):
mcov-minecraft         |   File "/usr/bin/overviewer.py", line 650, in <module>
mcov-minecraft         |     ret = main()
mcov-minecraft         |   File "/usr/bin/overviewer.py", line 443, in main
mcov-minecraft         |     assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
mcov-minecraft         |   File "/usr/lib/python3.5/dist-packages/overviewer_core/assetmanager.py", line 47, in __init__
mcov-minecraft         |     self.fs_caps = get_fs_caps(self.outputdir)
mcov-minecraft         |   File "/usr/lib/python3.5/dist-packages/overviewer_core/files.py", line 27, in get_fs_caps
mcov-minecraft         |     return {"chmod_works": does_chmod_work(dir_to_test),
mcov-minecraft         |   File "/usr/lib/python3.5/dist-packages/overviewer_core/files.py", line 38, in does_chmod_work
mcov-minecraft         |     f1 = tempfile.NamedTemporaryFile(dir=dir_to_test)
mcov-minecraft         |   File "/usr/lib/python3.5/tempfile.py", line 688, in NamedTemporaryFile
mcov-minecraft         |     (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
mcov-minecraft         |   File "/usr/lib/python3.5/tempfile.py", line 399, in _mkstemp_inner
mcov-minecraft         |     fd = _os.open(file, flags, 0o600)
mcov-minecraft         | PermissionError: [Errno 13] Permission denied: '/home/minecraft/render/tmp2a3jb9t2'
mcov-minecraft exited with code 1
```

Here's the relevant part of the docker-compose.yml I am using for this:

```
  mcov-minecraft:
    image: mide/minecraft-overviewer:latest
    container_name: mcov-minecraft
    networks:
      - mc
    restart: always
    volumes:
      - /home/someuser/mc-minecraft:/home/minecraft/server/:ro
      - ./mcov/render/minecraft:/home/minecraft/render/:rw
    environment:
      - MINECRAFT_VERSION=1.15.2
```

**Comment by mide** [comment]
Looks like a permissions error, perhaps on the mount point. The project could likely benefit from some better documentation around that. I haven't had a chance to look, but hope to soon.

**Comment by mide** [comment]
Possibly related to #8?

**Comment by mide** [comment]
Are you still having permission problems? I have not yet had a chance to update the documentation.

**Comment by anLizard** [comment]
Sorry, didn't get a chance to try again yet... I'll update you when I did it!

**Comment by anLizard** [comment]
Not sure what I did, but I am now getting a permission error when it is trying to create the folder for the version it is trying to download.
I tried chowning the folder recursively with my user, but the problem persists.

```
Using Client URL https://launcher.mojang.com/v1/objects/e3f78cd16f9eb9a52307ed96ebec64241cc5b32d/client.jar to download 1.15.2.jar.
mkdir: cannot create directory '/home/minecraft/.minecraft/versions/1.15.2/': Permission denied
```

docker-compose.yml:
```
  mcov:
    image: mide/minecraft-overviewer:latest
    container_name: mcov
    volumes:
      - ./mcov/versions:/home/minecraft/.minecraft/versions/
      - ./mcov/render/squad:/home/minecraft/render/
      - /home/mc:/home/minecraft/server:ro
    environment:
      - MINECRAFT_VERSION=1.15.2
```
